
# added by Miniconda2 3.19.0 installer
export PATH="/Users/pjm/miniconda2/bin:$PATH"

# LSST setup:
source activate lsst
source eups-setups.sh
setup obs_lsstSim
setup lsst_sims

# LSST DESC setup:
source ${TWINKLES_DIR}/setup/setup.sh
source ${MONITOR_DIR}/setup/setup.sh

# added by Miniconda3 installer
export PATH="/Users/pjm/miniconda3/bin:$PATH"

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/pjm/anaconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/pjm/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/Users/pjm/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/Users/pjm/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

